export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<main
			className="nfts"
			data-group="parent"
			style={{
				marginTop: "8rem",
			}}
		>
			{children}
		</main>
	);
}
